### ISSUE TITLE
Error  on schema registry when re-publishing an AVRO schema with nested objects

### ISSUE THREAD

**Issue by aivaldi** [specmesh/specmesh-build#401]
Having a specmesh definition of two topics with schemaLookupStrategy set as **RecrodNameStrategy** and one of the AVRO schemas of a topic has a nested schema that is also published with same strategy, fails to re-publish the schema.
It works as expected the first time but if you try to publish it again(with no changes) then an exception is thrown.  

**To Reproduce**

1. Create a simple schema
2. Create a schema that uses the simple schema
3. Create a specmesh definition with two topics one for each schema and set the strategy as  **RecrodNameStrategy**
4. Execute the command to provisioning the topics and the scehmas
5. Check schemas are created and the nested schema with reference.
6. Execute the command to provisioning the topics one more time
7. The execution fails, it can resolve the reference in the schema 

**Expected behavior**
Execution should not fail and schema should be updated or not modified.

**Actual behaviour**
Fails with an exception in Avro parser, since it can't resolve the nested schema.

**Version info**
- What version of SpecMesh is affected? Using docker image 
- What OS are you on? mac os

**Additional context**
This happens when it's parsing the avro schema that fetched from the schema registry, since it's contains references, when parsing it, it's not taking in consideration those references.

**Comment by big-andy-coates** [comment]
Looks like SpecMesh isn't correctly handling nested schemas. It needs to detect and register nested schemas depth-first.

Personally, I think it's valid to detect and register nested schemas, where those schemas are under the domains namespace. It shouldn't register schemas that live under a different namespace, e.g. shared / common schema.
