### ISSUE TITLE
AVRO Schemas with more than one level of recursion are not correctly published in the schema registry.

### ISSUE THREAD

**Issue by aivaldi** [specmesh/specmesh-build#402]
**Describe the bug**
Having three Avro schemas i.e A,B,C where C contains B, B contains A,  each nested reference is using **"subject"** as field to solve the reference and a schema definition where we have three of them defined using schemaLookupStrategy:RecordNameStrategy.
The provisioning is failing when processing C because A is not defined in the schema B. Seems like is not posible to resolve the schema A once it reads B from C, but it can resolve it when reads B directly

**To Reproduce**

1. Create three nested scehmas like in the descirption
2. Create a specmesh definition where the three of them are published and with RecordNameStrategy
3. Execut the client
4. It will file when parsing one of the schemas 

**Expected behavior**
Be able to resolve all the nested references

**Actual behaviour**
It can resolve reference when a nested schema  use a schema with nested references

**Version info**
- What version of SpecMesh is affected? 0.9.4 and 0.12.1
- What OS are you on? mac

**Additional context**
The iteration of the schemas is not recursive so is only processing the first schema properly and the parse method is breaking here https://github.com/specmesh/specmesh-build/blob/main/kafka/src/main/java/io/specmesh/kafka/provision/schema/SchemaReaders.java#L98

**Comment by big-andy-coates** [comment]
@aivaldi can you please provide example spec and schemas please?
