### ISSUE TITLE
Remove ACLs on deployment if `grant-access` removed.

### ISSUE THREAD

**Issue by big-andy-coates** [specmesh/specmesh-build#57]
When deploying later versions of a spec, it may be the case that a `grant-access` has been removed.  We'll need to remove the ACL to ensure we keep things locked down.

We should do this by inspecting the ACLs on each owned topic and removing any `DESCRIBE` and `READ` ACLs for users no in our list.

**Comment by bluemonk3y** [comment]
addressed as part of this: #211
