### ISSUE TITLE
Allow domains to create private topics not in the spec

### ISSUE THREAD

**Issue by big-andy-coates** [specmesh/specmesh-build#61]
Think... Kafka Streams repartition and changelog topics.  These are created by KS's using an admin client (i.e. they avoid auto topic creation on the broker).

**Comment by bluemonk3y** [comment]
@big-andy-coates  - what about prefixing... if they are prefixed with their domain then shouldn't it be ok? At least that provides a constraint that can be ACLd

**Comment by big-andy-coates** [comment]
Yep, exactly.
