### ISSUE TITLE
Extract production consumption metrics per-app to support chargeback modelling 

### ISSUE THREAD

**Issue by bluemonk3y** [specmesh/specmesh-build#84]
**Is your feature request related to a problem? Please describe.**
We want to provide enough snapshot metrics to allow a chargeback model to be built/derived. The first phase will break down per-topic-partition snapshot of the number of 'records' at the current offset. 

**Describe the solution you'd like**
the ability to one-shot execute the code to extract current topic-partition-offset starts at time 't'. 
Further augmentation will capture per-topic-bytes (similar to kafka.admin.LogDirsCommand) - from which the average record size can be calculated. Compacted topics are problematic and 

**Additional context**
We need a simple method that captured sufficient cluster/topic/consumer metrics to build chargeback modeling. The first phase is to calculate topic-partition level records, and derive record size. From this - throughput and volume can be derived. Compacted topics are problematic and may require segment investigation

@big-andy-coates  - wdyt?

**Comment by big-andy-coates** [comment]
Arguably many more important things to work on first.

That aside, like good.
The admin api provides some info on log dirs on each broker. _Might_ be enough to build a picture of disk utilisation and message rates.

Message rates and data sizes would allow for basic charge back model.

However... This is moving more into cluster monitoring, which is far away from SpecMesh core value IMHO.

**Comment by bluemonk3y** [comment]
As discussed - we want to be aligned with a data-product product (primarily around public topics) and their utlisation, so it sits on the specmesh modeling semantic, along with topological views, and observability... ;)

**Comment by bluemonk3y** [comment]
Left open until the doc task is complete
